-- =========================================================
-- Sistema Inventario - Oracle
-- Esquema de base de datos
--
-- IMPORTANTE:  Ejecutar este script solo si se esta
--              creando una nueva base de datos.
--
-- v1.0
-- Creación del esquema inicial
-- =========================================================

-- Si se está creando una nueva base de datos, 
-- descomentar las siguientes líneas para crear un esquema dedicado

-- CREATE USER INVENTARIO IDENTIFIED BY "--password--";
-- GRANT CONNECT, RESOURCE TO INVENTARIO;
-- ALTER USER INVENTARIO QUOTA UNLIMITED ON USERS;


-- Bodegas
CREATE TABLE WAREHOUSES (
  ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NAME         VARCHAR2(120)   NOT NULL,
  LOCATION     VARCHAR2(250),
  ENABLED      CHAR(1)         DEFAULT 'S' CHECK (ENABLED IN ('S','N')),
  CREATED_AT   TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL
);


-- Productos
CREATE TABLE PRODUCTS (
  ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  SKU          VARCHAR2(40),
  NAME         VARCHAR2(200)   NOT NULL,
  CATEGORY     VARCHAR2(100),
  PRICE        NUMBER(12)      NOT NULL CHECK (PRICE >= 0),
  ENABLED      CHAR(1)         DEFAULT 'S' CHECK (ENABLED IN ('S','N')),
  WAREHOUSE_ID NUMBER          NOT NULL,
  CREATED_AT   TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT FK_PRODUCTS_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(ID)
);

-- Búsqueda por bodega
CREATE INDEX IX_PRODUCTS_WAREHOUSE ON PRODUCTS (WAREHOUSE_ID);
CREATE INDEX IX_PRODUCTS_SKU ON PRODUCTS (SKU);
CREATE INDEX IX_PRODUCTS_NAME ON PRODUCTS (NAME);


