-- =========================================================
-- Sistema Inventario - Oracle
-- Esquema de base de datos
--
-- IMPORTANTE:  Ejecutar este script solo si se esta actualizando
--              o creando una nueva base de datos.
--
-- v1.1.b - Datos de prueba
--          SOLO EJECUTAR DESPUES DE v1.1.a
-- =========================================================


------------------------------------------------------------
-- 0) Limpieza de datos previos (si es necesario)
------------------------------------------------------------
-- DELETE FROM STOCK_MOVEMENTS;
-- DELETE FROM RESERVATIONS;
-- DELETE FROM ORDER_LINES;
-- DELETE FROM ORDERS;
-- DELETE FROM STOCKS;
-- DELETE FROM PRODUCTS;
-- DELETE FROM WAREHOUSES;
-- DELETE FROM ORDER_STATUS;
-- DELETE FROM ORDER_TYPE;
-- DELETE FROM ORDER_LINE_STATUS;
-- DELETE FROM RESERVATION_STATUS;
-- DELETE FROM MOVEMENT_TYPE;
-- COMMIT;


------------------------------------------------------------
-- 1) Tablas parametricas
------------------------------------------------------------

-- -- ORDER_STATUS
-- INSERT INTO ORDER_STATUS (ID, CODE, DESCRIPTION) VALUES (1, 'DRAFT',     'Borrador');
-- INSERT INTO ORDER_STATUS (ID, CODE, DESCRIPTION) VALUES (2, 'CONFIRMED', 'Confirmada');
-- INSERT INTO ORDER_STATUS (ID, CODE, DESCRIPTION) VALUES (3, 'ALLOCATED', 'Con reservas');
-- INSERT INTO ORDER_STATUS (ID, CODE, DESCRIPTION) VALUES (4, 'SHIPPED',   'Despachada');
-- INSERT INTO ORDER_STATUS (ID, CODE, DESCRIPTION) VALUES (5, 'CLOSED',    'Cerrada');
-- INSERT INTO ORDER_STATUS (ID, CODE, DESCRIPTION) VALUES (6, 'CANCELED',  'Cancelada');


-- -- ORDER_TYPE
-- INSERT INTO ORDER_TYPE (ID, CODE, DESCRIPTION) VALUES (1, 'SALES',    'Venta a cliente');
-- INSERT INTO ORDER_TYPE (ID, CODE, DESCRIPTION) VALUES (2, 'PURCHASE', 'Compra a proveedor');
-- INSERT INTO ORDER_TYPE (ID, CODE, DESCRIPTION) VALUES (3, 'TRANSFER', 'Traslado interno');


-- -- ORDER_LINE_STATUS
-- INSERT INTO ORDER_LINE_STATUS (ID, CODE, DESCRIPTION) VALUES (1, 'PENDING',   'Pendiente');
-- INSERT INTO ORDER_LINE_STATUS (ID, CODE, DESCRIPTION) VALUES (2, 'RESERVED',  'Reservada');
-- INSERT INTO ORDER_LINE_STATUS (ID, CODE, DESCRIPTION) VALUES (3, 'SHIPPED',   'Despachada');
-- INSERT INTO ORDER_LINE_STATUS (ID, CODE, DESCRIPTION) VALUES (4, 'BACKORDER', 'Pendiente por falta de stock');
-- INSERT INTO ORDER_LINE_STATUS (ID, CODE, DESCRIPTION) VALUES (5, 'CANCELED',  'Cancelada');


-- -- RESERVATION_STATUS
-- INSERT INTO RESERVATION_STATUS (ID, CODE, DESCRIPTION) VALUES (1, 'OPEN',     'Vigente');
-- INSERT INTO RESERVATION_STATUS (ID, CODE, DESCRIPTION) VALUES (2, 'CONSUMED', 'Consumida en despacho');
-- INSERT INTO RESERVATION_STATUS (ID, CODE, DESCRIPTION) VALUES (3, 'CANCELED', 'Anulada');
-- INSERT INTO RESERVATION_STATUS (ID, CODE, DESCRIPTION) VALUES (4, 'EXPIRED',  'Expirada');


-- MOVEMENT_TYPE
INSERT INTO MOVEMENT_TYPE (ID, CODE, DESCRIPTION) VALUES (1, 'RECEIVE',      'Recepción/Entrada');
INSERT INTO MOVEMENT_TYPE (ID, CODE, DESCRIPTION) VALUES (2, 'SHIP',         'Despacho/Salida');
INSERT INTO MOVEMENT_TYPE (ID, CODE, DESCRIPTION) VALUES (3, 'ADJUST',       'Ajuste de inventario');
INSERT INTO MOVEMENT_TYPE (ID, CODE, DESCRIPTION) VALUES (4, 'TRANSFER_OUT', 'Salida a traslado');
INSERT INTO MOVEMENT_TYPE (ID, CODE, DESCRIPTION) VALUES (5, 'TRANSFER_IN',  'Entrada de traslado');


------------------------------------------------------------
-- 2) Bodegas
------------------------------------------------------------
INSERT INTO WAREHOUSES (ID, NAME, LOCATION, ENABLED, IS_PRIMARY, CREATED_AT)
VALUES (1, 'Bodega Central',   'Av. Providencia 1234, Santiago', 'S', 'S', SYSTIMESTAMP);

INSERT INTO WAREHOUSES (ID, NAME, LOCATION, ENABLED, IS_PRIMARY, CREATED_AT)
VALUES (2, 'Bodega Secundaria','Camino Industrial 456, Quilicura', 'S', 'N', SYSTIMESTAMP);


------------------------------------------------------------
-- 3) Productos
------------------------------------------------------------
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (101, 'KB-001', 'Teclado Mecánico RGB', 'Periféricos', 45990, 'S', SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (102, 'MS-002', 'Mouse Inalámbrico Logitech', 'Periféricos', 22990, 'S', SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (103, 'HD-003', 'Disco Duro Externo 1TB', 'Almacenamiento',55990, 'S', SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (104, 'MN-004', 'Monitor LED 24"', 'Pantallas', 129990, 'S', SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (201, 'LT-005', 'Notebook Lenovo i5 8GB RAM', 'Computadores', 459990, 'S', SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (202, 'PR-006', 'Impresora Multifuncional HP', 'Impresoras', 89990, 'S', SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (203, 'UP-007', 'UPS 1200VA Forza', 'Energía', 75990, 'S', SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE, ENABLED, CREATED_AT)
VALUES (204, 'RO-008', 'Router TP-Link WiFi 6', 'Redes', 65990, 'S', SYSTIMESTAMP);


------------------------------------------------------------
-- 4) Stock
------------------------------------------------------------
-- Bodega 1
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (101, 1, 50, 5);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (102, 1, 80, 10);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (103, 1, 20, 0);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (104, 1, 15, 2);

-- Bodega 2
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (101, 2, 10, 0);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (103, 2, 30, 5);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (104, 2, 5,  0);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (201, 2, 12, 0);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (202, 2, 25, 3);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (203, 2, 7,  0);
INSERT INTO STOCKS (PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED) VALUES (204, 2, 18, 1);

/*
------------------------------------------------------------
-- 5) Orders
------------------------------------------------------------
-- Orden de venta 1001 (confirmada, promesa en 2 días)
INSERT INTO ORDERS (
  ID, ORDER_TYPE_ID, STATUS_ID, CUSTOMER_REF, PRIORITY,
  REQUESTED_AT, PROMISED_AT, COMPLETED_AT, CANCELED_AT, CREATED_AT, UPDATED_AT
) VALUES (
  1001, 1, 2, 'WEB-0001', 1,
  TO_TIMESTAMP('2025-09-07 09:30:00','YYYY-MM-DD HH24:MI:SS'),
  TO_TIMESTAMP('2025-09-09 18:00:00','YYYY-MM-DD HH24:MI:SS'),
  NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP
);

-- Líneas (resumen: mucho teclado para forzar split 30+10, monitor desde B1, notebook desde B2)
INSERT INTO ORDER_LINES (ID, ORDER_ID, PRODUCT_ID, QTY, STATUS_ID, NOTE)
VALUES (10011, 1001, 101, 40, 2, 'Teclado mecánico - requiere split entre B1 y B2'); -- RESERVED
INSERT INTO ORDER_LINES (ID, ORDER_ID, PRODUCT_ID, QTY, STATUS_ID, NOTE)
VALUES (10012, 1001, 104,  8, 2, 'Monitores LED 24"');                                -- RESERVED
INSERT INTO ORDER_LINES (ID, ORDER_ID, PRODUCT_ID, QTY, STATUS_ID, NOTE)
VALUES (10013, 1001, 201,  2, 2, 'Notebooks Lenovo i5');                              -- RESERVED

------------------------------------------------------------
-- 6) RESERVATIONS (resultado de allocation por bodega)
--    101: 30 de B1 + 10 de B2
--    104: 8 de B1
--    201: 2 de B2
------------------------------------------------------------
INSERT INTO RESERVATIONS (ID, ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, WAREHOUSE_ID, QTY, STATUS_ID, EXPIRES_AT, CREATED_AT)
VALUES (5001, 1001, 10011, 101, 1, 30, 1, TO_TIMESTAMP('2025-09-09 12:00:00','YYYY-MM-DD HH24:MI:SS'), SYSTIMESTAMP);

INSERT INTO RESERVATIONS (ID, ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, WAREHOUSE_ID, QTY, STATUS_ID, EXPIRES_AT, CREATED_AT)
VALUES (5002, 1001, 10011, 101, 2, 10, 1, TO_TIMESTAMP('2025-09-09 12:00:00','YYYY-MM-DD HH24:MI:SS'), SYSTIMESTAMP);

INSERT INTO RESERVATIONS (ID, ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, WAREHOUSE_ID, QTY, STATUS_ID, EXPIRES_AT, CREATED_AT)
VALUES (5003, 1001, 10012, 104, 1,  8, 1, TO_TIMESTAMP('2025-09-09 12:00:00','YYYY-MM-DD HH24:MI:SS'), SYSTIMESTAMP);

INSERT INTO RESERVATIONS (ID, ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, WAREHOUSE_ID, QTY, STATUS_ID, EXPIRES_AT, CREATED_AT)
VALUES (5004, 1001, 10013, 201, 2,  2, 1, TO_TIMESTAMP('2025-09-09 12:00:00','YYYY-MM-DD HH24:MI:SS'), SYSTIMESTAMP);

-- Reflejar reservas en STOCKS (incremento de RESERVED)
UPDATE STOCKS SET RESERVED = RESERVED + 30, UPDATED_AT = SYSTIMESTAMP WHERE PRODUCT_ID = 101 AND WAREHOUSE_ID = 1;
UPDATE STOCKS SET RESERVED = RESERVED + 10, UPDATED_AT = SYSTIMESTAMP WHERE PRODUCT_ID = 101 AND WAREHOUSE_ID = 2;
UPDATE STOCKS SET RESERVED = RESERVED +  8, UPDATED_AT = SYSTIMESTAMP WHERE PRODUCT_ID = 104 AND WAREHOUSE_ID = 1;
UPDATE STOCKS SET RESERVED = RESERVED +  2, UPDATED_AT = SYSTIMESTAMP WHERE PRODUCT_ID = 201 AND WAREHOUSE_ID = 2;

-- (Opcional) actualizar estado de la orden a ALLOCATED
UPDATE ORDERS SET STATUS_ID = 3, UPDATED_AT = SYSTIMESTAMP WHERE ID = 1001;

------------------------------------------------------------
-- 7) STOCK_MOVEMENTS (una recepción para mostrar escritura)
------------------------------------------------------------
INSERT INTO STOCK_MOVEMENTS (
  ID, PRODUCT_ID, WAREHOUSE_ID, MOV_TYPE_ID, QTY, REFERENCE, ORDER_ID, ORDER_LINE_ID, CREATED_AT
) VALUES (
  9001, 103, 1, 1, 10, 'RCV-PO-789', NULL, NULL, SYSTIMESTAMP
);

-- Aplicar la recepción sobre STOCKS (suma a ON_HAND)
UPDATE STOCKS
   SET ON_HAND = ON_HAND + 10,
       UPDATED_AT = SYSTIMESTAMP
 WHERE PRODUCT_ID = 103 AND WAREHOUSE_ID = 1;

COMMIT;

------------------------------------------------------------
-- 8) Consultas rápidas de verificación (ejecútalas a mano)
------------------------------------------------------------
-- Stock por producto/bodega (muestra available)
-- SELECT PRODUCT_ID, WAREHOUSE_ID, ON_HAND, RESERVED, AVAILABLE FROM STOCKS ORDER BY PRODUCT_ID, WAREHOUSE_ID;

-- Orden 1001 con líneas
-- SELECT * FROM ORDERS WHERE ID = 1001;
-- SELECT * FROM ORDER_LINES WHERE ORDER_ID = 1001 ORDER BY ID;
-- SELECT ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, WAREHOUSE_ID, QTY, STATUS_ID FROM RESERVATIONS WHERE ORDER_ID = 1001 ORDER BY ID;
